### ISSUE TITLE
default value for pla input

### ISSUE THREAD

**Issue by deepansktm** [psksvp/espresso-ab-1.0#1]
Hi,

Is there any option to specify a default value for a function in a pla input file for espresso?

For eg: in case of pla below,instead of listing out the entire truth-table, Can I define default value as one for all cases except(0000 and 0001) so that I need not list all the cases

      -----------------------------
      .i 4
      .o 2
      0000  10
      0001  10
      0010  01
      0011  01
      0100  01
      0101  01
      0110  01
      0111  01
      1000 01
      1001 01
      1010 01
      1011 01
      1100 01
      1101 01
      1110 01
      1111 01
      .e
      ----------------------------

**Comment by psksvp** [comment]
I don't think there is such feature as far as I know. However, you can just write a script to generate the pla with whatever you need and pipe it thru espresso. 

This is not an issue, please use the wiki.
